import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useWeb3 } from "@3rdweb/hooks";

export default function Home() {
  const { address, connectWallet } = useWeb3();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {address ? (
          <>
            <div className="flex h-[100vh] justify-center items-center">
              <h1>Logged in with {address}</h1>
            </div>
          </>
        ) : (
          <div className="flex h-[100vh] justify-center items-center">
            <button
              className="bg-blue-900 p-10 font-bold text-3xl rounded-md"
              onClick={() => connectWallet("injected")}
            >
              Login To Metamask
            </button>
          </div>
        )}
      </main>
    </div>
  );
}
